### ISSUE TITLE
Fix tests?

### ISSUE THREAD

**Issue by imagejan** [scijava/javadoc.scijava.org#6]
The Travis CI build currently [fails](https://travis-ci.com/scijava/javadoc.scijava.org/builds/134775076) because all the redirects show the original (redirect-target) URLs instead of `https://javadoc.scijava.org/{project}`.

@ctrueden Should we update the tests, or are you planning to fix the redirects to actually rewrite the URLs?

**Comment by ctrueden** [comment]
I am planning to fix the redirects on the server side.

**Comment by ctrueden** [comment]
I fixed the redirect rule on the server side. It was a bug in the rule that added a trailing slash when one was missing.
